services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/ssl/
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/home/node
    env_file:
    - .env
    # Run a command against the development stage of the image
    command: yarn run start:prod 
    ports:
      - 9001:9001
